### ISSUE TITLE
Flashing Esp-Link in Windows?

### ISSUE THREAD

**Issue by darkipod** [jeelabs/esp-link#127]
Im trying to flash the ESP-link files to my esp8266-01 in windows, Im currently writing all the files but after it does not give me anything on the status LED and I see no access point.

**Comment by WheresWally** [comment]
You should be able to see debug data from the ESP8266 while it sets up. So after flashing, reset it, remove the FLASH jumper if that is how you get the ESP8266 to be in flash mode, and leave it hooked to the serial port of the computer, open a terminal at 115200 to that port, then reset the ESP8266.
Maybe you can post what you see there so the gurus can help you.

**Comment by SloMusti** [comment]
Encountered the same problem with v2.1.7 when flashing using ESP tool on Windows on Nodemcu V2. UART debug on reset does not print out any logs, just some gibberish immediately after reset button is pressed.

The problem was in my case an old version of ESP Flasher tool, using the latest version from https://github.com/nodemcu/nodemcu-flasher solved the problem. @darkipod try this

After successful flash I get the serial output via USB.

**Comment by tve** [comment]
Closing ticket: there's nothing actionable for me. Feel free to reopen.
