### ISSUE TITLE
Using esp-link with PWM?

### ISSUE THREAD

**Issue by snblitz** [jeelabs/esp-link#177]
I am using PWM along with jeelabs esp-link. I am getting a slightly odd waveform on my oscope. I am attempting to generate a 1KHz square wave.
![oddwaveform](https://cloud.githubusercontent.com/assets/4516175/17794680/786c3e24-6566-11e6-92e9-dd2c8b1ffa5b.jpg)

![Uploading oddwaveform.jpg…]()

The "spike" is 2.2us long and the time to the following rising edge is 70us.  I have the same behavior on 3 output pins with various duty cycles.

```
#include "pwm.h"
uint32 io_info[][PWM_CHANNELS] = {
    {PWM_0_OUT_IO_MUX,PWM_0_OUT_IO_FUNC,PWM_0_OUT_IO_NUM},
    {PWM_1_OUT_IO_MUX,PWM_1_OUT_IO_FUNC,PWM_1_OUT_IO_NUM},
    {PWM_2_OUT_IO_MUX,PWM_2_OUT_IO_FUNC,PWM_2_OUT_IO_NUM}
};
uint32 pwm_period = 1000; //us

uint32 pwm_duty_init[PWM_CHANNELS] = { 0, 0, 0 };

void
app_init() {
    pwm_init(pwm_period, pwm_duty_init, PWM_CHANNELS, io_info);
    set_pwm_debug_en(0);
    pwm_set_duty(5555,0);
    pwm_set_duty(2*5555,1);
    pwm_set_duty(3*5555,2);
    pwm_start();
}

```

**Comment by tve** [comment]
Looks like no-one has commented on this. I'm afraid I don't have much to say. I haven't played with PWM on the esp8266 because I've read too many horror stories. I'm afraid PWM is just not very usable and what you're seeing is what many others have seen too... I'm going to close this issue 'cause it's a bit too far off in left field for esp-link. Sorry.
