### ISSUE TITLE
Enhancement: snooping mode

### ISSUE THREAD

**Issue by sle118** [jeelabs/esp-link#278]
I am suggesting that esp-link implements a snoop mode to allow sniffing on serial protocol conversations. This would be extremely useful when debugging/analyzing conversations between devices without disrupting them.  Telnet would log data from one of the device's point of view with tags like TX/RX prefixing lines.

**Comment by hexagon5un** [comment]
(I'm not related to the project other than being a happy user.)

Snooping one line is easy -- just attach an ESP-link RX pin to it and turn off the pullup.  Snooping two is left as an exercise to the motivated reader. 

Seriously -- the UART hardware TX line doesn't do receive natively, so this would have to be done in software.    This should be doable, but it's a different device altogether and a reasonable code project.  Throwing another ESP at the problem is probably the easy way out.

**Comment by tve** [comment]
The esp8266 only has a single usable uart RX pin, so you would only be able to snoop one line, which is not what you're looking for, if I understand correctly.

**Comment by sle118** [comment]
@tve i was thinking along the lines of soft serial, actually, using one of the very few pins of the esp8266
